apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      {{- include "qbittorrent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "qbittorrent.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "qbittorrent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.web.port }}
              protocol: TCP
            - name: torrent-tcp
              containerPort: {{ .Values.service.torrent.port }}
              protocol: TCP
            - name: torrent-udp
              containerPort: {{ .Values.service.torrent.port }}
              protocol: UDP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: QBITTORRENT__PORT
              value: "{{ $.Values.service.web.port }}"
            - name: QBITTORRENT__BT_PORT
              value: "{{ $.Values.service.torrent_port }}"

          {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.config.persistence.enabled .Values.volumeMounts }}
          volumeMounts:
          {{- if .Values.config.persistence.enabled }}
            - name: config
              mountPath: /config
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
        {{- if .Values.gluetun.enabled }}
        - name: gluten
          securityContext:
            {{- toYaml .Values.gluetun.securityContext | nindent 12 }}
          {{- if .Values.gluetun.image.sha }}
          image: "{{ .Values.gluetun.image.registry }}/{{ .Values.gluetun.image.repository }}:{{ .Values.gluetun.image.tag }}@sha256:{{ .Values.gluetun.image.sha }}"
          {{- else }}
          image: "{{ .Values.gluetun.image.registry }}/{{ .Values.gluetun.image.repository }}:{{ .Values.gluetun.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.gluetun.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $.Values.service.web.port }}
              protocol: TCP
            - name: shadowsocks-tcp
              containerPort: 8388
              protocol: TCP
            - name: shadowsocks-udp
              containerPort: 8388
              protocol: UDP
          resources:
            {{- toYaml .Values.gluetun.resources | nindent 12 }}
          {{- with .Values.gluetun.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.gluetun.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.gluetun.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- if or .Values.config.persistence.enabled .Values.volumes }}
      volumes:
      {{- if .Values.config.persistence.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "qbittorrent.configPersistenceName" . }}
      {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
